openapi: 3.0.0
info:
  title: Guess The Number API
  description: API для гри "Вгадай число"
  version: 1.0.0
servers:
  - url: http://localhost:3000

paths:
  /game/start:
    post:
      summary: Почати нову гру
      description: Генерує випадкове число від 1 до 100.
      responses:
        200:
          description: Успішний початок гри
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Гру розпочато! Вгадайте число від 1 до 100."
                required:
                  - message

  /game/guess:
    post:
      summary: Надіслати спробу
      description: Перевіряє, чи вгадано число.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                guess:
                  type: integer
                  minimum: 1
                  maximum: 100
                  example: 42
              required:
                - guess
      responses:
        200:
          description: Результат спроби
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum: [correct, low, high]
                    example: "low"
                  message:
                    type: string
                    example: "Спробуйте більше число."
                required:
                  - result
                  - message
        400:
          description: Помилка
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Некоректне число (1-100)"
                required:
                  - message